# Site settings
baseurl = "http://replace-this-with-your-hugo-site.com/"
languageCode = "en-us"
title = "Determinate Stoic"
theme = "hugo-highlights-theme"

# Enter your tracking code to enable Google analytics
googleAnalytics = "UA-79936510-1"

[params]

  # You can use Markdown for urls [text](//domain.tld/source)
  #
  # All icons using Fontawesom's icon font. Look at fortawesome.github.io/Font-Awesome/icons/
  # for more icons.

  # To provide more meta data for search engings feel free to add a few informations.
  # This lines will be inserted as meta tags.
  name = "Ari M. Nazir"
  description = "I am a Determinate Stoic"

  # For a static site it's not possible to provide a contact form. The contact form uses
  # www.formspree.io as a proxy. The form makes a Post request to their servers to send an email
  # Visitors can send up to a 1000 emails each month
  #
  # How to setup formspree
  #
  # - set your email address under 'email' below
  # - upload the generated site to your server
  # - send a dummy email to yourself to confirm your account
  # - click the confirmation link in the email from www.formspree.io
  # - That's all. Enjoy mailing!
  email = "arij.m.nazir@gmail.com"

  # Hero Section
  [params.hero]
    title = "Determinate Stoic"
    description = Welcome to the Determinate Stoic"
    buttonText = "begin"

  # about section
  [params.about]
    enable = true
    title = "What is a Determinate Stoic"
    description = "A Determinate Stoic exists at the intersection of mindfulness, ambition, grit, and peace."
    buttonText = "next"
    # the picture is stored at static/images/
    picture = "pic01.jpg"

  # skill section
  [params.skill_list]
    enable = true
    title = "Current Happenings"
    description = "Work, Work, Work. Currently, I am accumulating total learning at the apex of technology and entrepreneurship."
    buttonText = "next"
    # the picture is stored at static/images/
    picture = "pic02.jpg"

    [[params.skills]]
      icon = "fa-camera-retro"
      title = "Paris"

    [[params.skills]]
      icon = "fa-pencil"
      title = "Burano"

    [[params.skills]]
      icon = "fa-code"
      title = "cinque terra"

    [[params.skills]]
      icon = "fa-coffee"
      title = "Petra"
  # infos section
  [params.infos]
    enable = true
    title = "My current interests include"
    description = "Entrepreneurship, Technology, Music, Travel, Finance, Systemic Policy, Neuroscience, Applied Philosophy, Applied Science, Yoga, Blockchain"
    # the picture is stored at static/images/
    picture = "pic03.jpg"

  # footer section
  # this section includes
  #
  # - the contact form
  # - social icons
  #
  # It's possible to disable the whole footer or disable only social icons or contact form

  [params.footer]
    enable = true
    title = "Connect with me"

    # contact form
    [params.footer.contact]
      enable = true

    [params.footer.contact.form]
      name = "Ari M. Nazir"
      email = "arij.m.nazir@gmail.com"
      message = "I'm reaching out to"
      buttonText = "Connect"

    # social icons
    [params.footer.social_list]
      enable = true

      [[params.footer.social]]
        title = "Twitter"
        icon = "fa-twitter"
        link = "https://twitter.com/AriMNazir"


      [[params.footer.social]]
        title = "Instagram"
        icon = "fa-instagram"
        link = "https://www.instagram.com/anazir/"

      [[params.footer.social]]
        title = "Medium"
        icon = "fa-Medium"
        link = "https://medium.com/@AriMNazir"

      [[params.footer.social]]
        title = "Email"
        icon = "fa-envelope"
        link = "arij.m.nazir@gmail.com"

    # copyright 2016
    #[params.footer.copyright.notice]

      [[params.footer.copyright.notice]]
        text = "© Nazir LLC"
